PJT_Inter/PJT_Inter/Models/OrdemServico.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PJT_Inter.Models
{
    public class OrdemServico
    {
        // Os(id, data_abertura, data_termino, data_entrega, equipamento, status, total, #cliente_codigo, #funcionario_codigo, #tecnico_codigo)
        public int Id { get; set; }

        [Required(ErrorMessage = "Campo cliente obrigatório")]
        public int Cliente_Codigo { get; set; }

        [Required(ErrorMessage = "Campo funcionario obrigatório")]
        public int Funcionario_Codigo { get; set; }

        public int Tecnico_Codigo { get; set; }

        [Display(Name = "Data da abertura")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Campo data abertura obrigatório")]
        public string Data_Abertura { get; set; }

        [Display(Name = "Data do termino")]
        [DataType(DataType.Date)]
        public string Data_Termino { get; set; }

        [Display(Name = "Data da entrega")]
        [DataType(DataType.Date)]
        public string Data_Entrega { get; set; }

        [Display(Name = "Descrição do equipamento")]
        [Required(ErrorMessage = "Campo equipamento obrigatório")]
        public string Equipamento { get; set; }

        [Display(Name = "Aberto/Aprovado/Finalizado/Cancelado")]
        [Required(ErrorMessage = "Campo status obrigatório")]
        public int Status { get; set; }

        [Display(Name = "Total")]
        [DataType(DataType.Currency)]
        public decimal? Total { get; set; }

        public string nomeCliente { get; set; }

        public string nomeTecnico { get; set; }

        public string nomeFuncionario { get; set; }

        public string StatusNome { get; set; }

        public bool existeServ { get; set; }
    }
}

PJT_Inter/PJT_Inter/Controllers/OrdemServicoController.cs
using Microsoft.AspNetCore.Mvc;
using PJT_Inter.Data;
using PJT_Inter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PJT_Inter.Controllers
{
    public class OrdemServicoController : Controller
    {
        public IActionResult Index()
        {
            using (var data = new OrdemServicoData())
                return View(data.Read());
        }

        public IActionResult Enviar(int id)
        {
            ViewBag.id_Os = id;
            return Redirect("/OsServ/Index/" + id);
        }


        public IActionResult Verificar(int id)
        {
            List<OsServ> oserv = new List<OsServ>();

            using (var data = new OrdemServicoData())
            {
                oserv = data.ExisteOk(id);
                if (oserv.Count() != 0)
                {
                    return Redirect("/OsServ/Update/" + id);
                }
                else
                {
                    return Redirect("/OsServ/Create/" + id);
                }
            }
        }
        public IActionResult Create(int id)
        {
            List<Cliente> clientes = new List<Cliente>();
            List<Tecnico> tecnicos = new List<Tecnico>();
            List<Funcionario> funcionarios = new List<Funcionario>();

            OrdemServico os = new OrdemServico();
            os.Cliente_Codigo = id;
            using (var data = new ClienteData())
            {
                clientes = data.BuscarClientes("");
                ViewBag.Clientes = clientes;

                var dataTec = new TecnicoData();
                tecnicos = dataTec.BuscarTecnicos("");
                ViewBag.Tecnicos = tecnicos;

                var dataFun = new FuncionarioData();
                funcionarios = dataFun.BuscarFuncionarios("");
                ViewBag.Funcionarios = funcionarios;

           
            }
            return View(os);
        }

        [HttpPost]
        public IActionResult Create(OrdemServico os)
        {
            using (var data = new OrdemServicoData())
                data.Create(os);

            return Redirect("/OrdemServico/Index");
        }

        public IActionResult Update(int id)
        {
            List<Tecnico> tecnicos = new List<Tecnico>();
            var dataTec = new TecnicoData();
            tecnicos = dataTec.BuscarTecnicos("");
            ViewBag.Tecnicos = tecnicos;

            using (var data = new OrdemServicoData())
                return View(data.Read(id));
        }
        [HttpPost]
        public IActionResult Update(int id, OrdemServico servico)
        {
            OrdemServico os = new OrdemServico();


            using (var data = new OrdemServicoData())
            {
                servico.Data_Abertura = data.BuscarDatas(id);
                data.Update(servico);
            }

            return RedirectToAction("Index");
        }
    }
}

PJT_Inter/PJT_Inter/Views/OrdemServico/Create.cshtml
@model OrdemServico

<h2>Cadastro - Ordem de Serviços</h2>
<form asp-controller="OrdemServico" asp-action="Create" method="post">
    <hr>

    <div class="form-group">

        <div class="form-group">
            <label>Cliente</label>
            

            <select asp-for="Cliente_Codigo" class="form-control">
                @foreach (var item in ViewBag.Clientes)
                {
                    
                    <option value="@item.Codigo">@item.Nome</option>
                }
            </select>
            
        </div>
        <label>Técnico</label>
        <select asp-for="Tecnico_Codigo" class="form-control">
            @foreach (var item in ViewBag.Tecnicos)
            {

                <option value="@item.Codigo">@item.Nome</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Funcionario</label>
        <select asp-for="Funcionario_Codigo" class="form-control">
            @foreach (var item in ViewBag.Funcionarios)
            {

                <option value="@item.Codigo">@item.Nome</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Equipamento</label>
        <input asp-for="Equipamento" class="form-control" placeholder="Equipamento" />
        <span asp-validation-for="Equipamento"></span>
    </div>

    <div class="form-group">
        <label asp-for="Data_Abertura"></label>
        <input asp-for="Data_Abertura" class="form-control" placeholder="Data Abertura" />
        <span asp-validation-for="Data_Abertura"></span>
    </div>
    <div class="form-group">
        <div class="form-check form-check-inline">
            <input asp-for="Status" checked type="radio" name="status" id="inlineCheckbox1" value="1">
            <span asp-validation-for="Status" style="margin-left: 5px">Ativo</span>
        </div>
    </div>

    <button class="btn btn-primary ">Salvar</button>
</form>

PJT_Inter/PJT_Inter/Views/OrdemServico/Index.cshtml
@model List<OrdemServico>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Lista de Ordem de Serviços
            <a class="btn btn-primary" style="float: right" href="/OrdemServico/Create">Adicionar</a></h6>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Nome Cliente</th>
                <th scope="col">Equipamento</th>
                <th scope="col">Data de Abertura</th>
                <th scope="col">Total</th>
                <th scope="col">Status</th>
                <th scope="col">Editar</th>
                <th scope="col">Serviços</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var os in Model)
            {
            <tr>
                <th scope="row">@os.Id</th>
                <th scope="row">@os.nomeCliente</th>
                <th scope="row">@os.Equipamento</th>
                <th scope="row">@os.Data_Abertura</th>
                <th scope="row">@Decimal.Round((decimal)os.Total, 2)</th>
                <th scope="row">@os.StatusNome</th>
                <th>
                    <a class="btn btn-info btn-circle btn-sm" href="/OrdemServico/Update/@os.Id">
                        <i class="fas fa-info-circle"></i>
                    </a>
                </th>
                <th>
                    <a class="btn btn-secondary btn-icon-split" href="/OrdemServico/Enviar/@os.Id">
                        <span class="icon text-white-50">
                            <i class="fas fa-arrow-right"></i>
                        </span>
                        <span class="text">Visualizar</span>
                    </a>
                </th>
            </tr>
            }
        </tbody>
    </table>
</div>

PJT_Inter/PJT_Inter/Views/OrdemServico/Update.cshtml
@model OrdemServico

<h2>Editar - Ordem de Serviços</h2>

<form asp-controller="OrdemServico" asp-action="Update" method="post">
    <hr />
    <input asp-for="Cliente_Codigo" type="hidden" />
    <div class="form-group">
        <label>Cliente</label>
        <input asp-for="nomeCliente" class="form-control" disabled placeholder="Nome" />
        <span asp-validation-for="nomeCliente"></span>
    </div>
    <div class="form-group">
        <label>Data de Abertura</label>
        <input asp-for="Data_Abertura" class="form-control" type="datetime" disabled />
        <span asp-validation-for="Data_Abertura"></span>
    </div>
    <input asp-for="Funcionario_Codigo" type="hidden" />
    <div class="form-group">
        <label>Funcionario</label>
        <input asp-for="nomeFuncionario" class="form-control" disabled placeholder="Funcionario" />
        <span asp-validation-for="nomeFuncionario"></span>
    </div>
    <label>Técnico</label>
    <select asp-for="Tecnico_Codigo" class="form-control">
        @foreach (var item in ViewBag.Tecnicos)
        {

            <option value="@item.Codigo">@item.Nome</option>
        }
    </select>
    <div class="form-group">
        <label>Equipamento</label>
        <input asp-for="Equipamento" class="form-control" placeholder="Equipamento" />
        <span asp-validation-for="Equipamento"></span>
    </div>
    <div class="form-group">
        <label>Total</label>
        <input asp-for="Total" class="form-control" placeholder="Equipamento" />
        <span asp-validation-for="Total"></span>
    </div>
    @if (Model.Data_Termino == null || Model.Data_Termino == "")
    {
        <div class="form-group">
            <label>Data de Termino</label>
            <input asp-for="Data_Termino" class="form-control" placeholder="Data Termino" />
            <span asp-validation-for="Data_Termino"></span>
        </div>
    }
    else
    {
        <div class="form-group">
            <label>Data de Termino</label>
            <input asp-for="Data_Termino" class="form-control" type="datetime" placeholder="Data Entrega" />
            <span asp-validation-for="Data_Termino"></span>
        </div>
    }
    @if (Model.Data_Entrega == null || Model.Data_Entrega == "")
    {
        <div class="form-group">
            <label>Data de Entrega</label>
            <input asp-for="Data_Entrega" class="form-control" placeholder="Data Entrega" />
            <span asp-validation-for="Data_Entrega"></span>
        </div>
    }
    else
    {
        <div class="form-group">
            <label>Data de Entrega</label>
            <input asp-for="Data_Entrega" class="form-control" type="datetime" placeholder="Data Entrega" />
            <span asp-validation-for="Data_Entrega"></span>
        </div>

    }

    <div class="form-group">
        <div class="form-check form-check-inline">
            <input asp-for="Status" type="radio" name="status" id="inlineCheckbox1" value="1">
            <span asp-validation-for="Status" style="margin-left: 5px">Aberto</span>
            <div class="form-check form-check-inline" style="margin-left: 10px">
                <input asp-for="Status" type="radio" name="status" id="inlineCheckbox1" value="2">
                <span asp-validation-for="Status" style="margin-left: 5px">Aprovado</span>
            </div>
            <div class="form-check form-check-inline" style="margin-left: 10px">
                <input asp-for="Status" type="radio" name="status" id="inlineCheckbox1" value="3">
                <span asp-validation-for="Status" style="margin-left: 5px">Finalizado</span>
            </div>
            <div class="form-check form-check-inline" style="margin-left: 10px">
                <input asp-for="Status" type="radio" name="status" id="inlineCheckbox1" value="4">
                <span asp-validation-for="Status" style="margin-left: 5px">Cancelado</span>
            </div>
        </div>
    </div>

    <button class="btn btn-primary ">Salvar</button>
</form>