PJT_Inter/PJT_Inter/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PJT_Inter.Models
{
    public class Funcionario : Pessoa
    {
        // Funcionarios (#Pessoa_codigo, senha, salario, status)
        public int Pessoa_Codigo { get; set; }

        [Display(Name = "Senha")]
        [Required(ErrorMessage = "Campo senha obrigatório")]
        [DataType(DataType.Password)]
        [MinLength(6)]
        public string Senha { get; set; }

        [Display(Name = "Salario")]
        [DataType(DataType.Currency)]
        public decimal Salario { get; set; }

        [Display(Name = "Ativo ou Inativo")]
        [Required(ErrorMessage = "Campo status obrigatório")]
        public int Status { get; set; }

        public string StatusNome { get; set; }
    }
}

PJT_Inter/PJT_Inter/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PJT_Inter.Data;
using PJT_Inter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PJT_Inter.Controllers
{
    public class FuncionarioController : Controller
    {
        public IActionResult index()
        {
            using (var data = new FuncionarioData())
                return View(data.Read());
        }
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public IActionResult Create(Funcionario funcionario)
        {
            if (!ModelState.IsValid)
            {
                return View(funcionario);
            }
            using (var data = new FuncionarioData())
                data.Create(funcionario);

            return RedirectToAction("Index");
        }
        public IActionResult Update()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            using (var data = new FuncionarioData())
                return View(data.Read(id));
        }

        [HttpPost]
        public IActionResult Update(int id, Funcionario funcionario)
        {
            funcionario.Pessoa_Codigo = id;
            if (funcionario.Senha == null)
            {
                FuncionarioData f = new FuncionarioData();
                funcionario.Senha = f.BuscaSenha(id);
                if (funcionario.Senha != "")
                {
                    using (var data = new FuncionarioData())
                        data.Update(funcionario);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(funcionario);
                }
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(funcionario);
                }

                using (var data = new FuncionarioData())
                    data.Update(funcionario);

                return RedirectToAction("Index");
            }
        }

        public IActionResult Login()
        {
            return View();
        }
        public IActionResult CreateLogin()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateLogin(Funcionario funcionario)
        {
            if (!ModelState.IsValid)
            {
                return View(funcionario);
            }
            using (var data = new FuncionarioData())
                data.Create(funcionario);

            return RedirectToAction("Login");
        }
        [HttpPost]
        public IActionResult Login(Funcionario funcionario)
        {
            if (funcionario.Email == null || funcionario.Senha == null)
            {
                return View("Login");
            }
            using (var data = new FuncionarioData())
                if (data.Login(funcionario.Email, funcionario.Senha))
                {
                    return Redirect("/Home/Index");
                }
                else
                {
                    ViewBag.Mensagem = "Email ou senha inválida";
                    return View("Login");
                }
        }
        public IActionResult Delete(int id)
        {
            using (var data = new FuncionarioData())
                data.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

PJT_Inter/PJT_Inter/Views/Funcionario/Create.cshtml
@model Funcionario
<h2>Cadastro - Funcionario</h2>


<form asp-controller="Funcionario" asp-action="Create" method="post">
    <hr>
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" placeholder="Nome" />
        <span asp-validation-for="Nome"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" placeholder="E-Mail" />
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="Senha"></label>
        <input asp-for="Senha" class="form-control" placeholder="Senha" />
        <span asp-validation-for="Senha"></span>
    </div>
    <div class="form-group">
        <label>Endereço</label>
        <input asp-for="Endereco" class="form-control" placeholder="Endereço" />
        <span asp-validation-for="Endereco"></span>
    </div>
    <div class="form-group">
        <div class="form-row">
            <div class="col">
                <label asp-for="CPF_CNPJ"></label>
                <input asp-for="CPF_CNPJ" class="form-control" placeholder="CPF/CNPJ">
                <span asp-validation-for="CPF_CNPJ"></span>
            </div>
            <div class="col">
                <label asp-for="Telefone"></label>
                <input asp-for="Telefone" class="form-control" placeholder="Telefone">
                <span asp-validation-for="Telefone"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="form-row">
            <div class="col">
                <label asp-for="Salario"></label>
                <input asp-for="Salario" class="form-control" placeholder="Salario">
                <span asp-validation-for="Salario"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="form-check form-check-inline">
            <input class="form-check-input" checked type="radio" name="status" id="inlineCheckbox1" value="1">
            <span asp-validation-for="Status">Ativo</span>
        </div>
    </div>
    <button class="btn btn-primary ">Salvar</button>
</form>

PJT_Inter/PJT_Inter/Views/Funcionario/CreateLogin.cshtml
@model Funcionario

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Crie a sua conta aqui!</h1>
                        </div>
                        <form asp-controller="Funcionario" asp-action="CreateLogin" method="post">
                            <div class="form-group">
                                <label asp-for="Nome"></label>
                                <input asp-for="Nome" class="form-control" placeholder="Nome" />
                                <span asp-validation-for="Nome"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Email"></label>
                                <input asp-for="Email" class="form-control" placeholder="E-Mail" />
                                <span asp-validation-for="Email"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CPF_CNPJ"></label>
                                <input asp-for="CPF_CNPJ" class="form-control" placeholder="CPF" />
                                <span asp-validation-for="CPF_CNPJ"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco"></label>
                                <input asp-for="Endereco" class="form-control" placeholder="Endereco" />
                                <span asp-validation-for="Endereco"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Salario"></label>
                                <input asp-for="Salario" class="form-control" placeholder="Salario" />
                                <span asp-validation-for="Salario"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Telefone"></label>
                                <input asp-for="Telefone" class="form-control" placeholder="Telefone" />
                                <span asp-validation-for="Telefone"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Senha"></label>
                                <input asp-for="Senha" type="password" class="form-control" placeholder="Senha">
                                <span asp-validation-for="Senha"></span>
                            </div>
                            <div class="form-group">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" checked type="radio" name="status" id="inlineCheckbox1" value="1">
                                    <span asp-validation-for="Status">Ativo</span>
                                </div>
                            </div>
                            <button class="btn btn-primary btn-user btn-block ">Salvar</button>
                            <hr>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PJT_Inter/PJT_Inter/Views/Funcionario/Index.cshtml
@model List<Funcionario>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            Lista de Funcionarios
            <a class="btn btn-primary" style="float: right" href="/Funcionario/Create">Adicionar</a>
        </h6>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Celular</th>
                <th scope="col">Status</th>
                <th scope="col">Editar</th>
                <th scope="col">Excluir</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var fun in Model)
            {
                <tr>
                    <th scope="row">@fun.Nome</th>
                    <th scope="row">@fun.Email</th>
                    <th scope="row">@fun.Telefone</th>
                    <th scope="row">@fun.StatusNome</th>
                    <th>
                        <a href="/Funcionario/Update/@fun.Codigo" class="btn btn-info btn-circle btn-sm">
                            <i class="fas fa-info-circle"></i>
                        </a>
                    </th>
                    <th>
                        <a href="/Funcionario/Delete/@fun.Codigo" class="btn btn-danger btn-circle btn-sm">
                            <i class="fas fa-trash"></i>
                        </a>
                    </th>

                </tr>
            }
        </tbody>
    </table>
</div>

PJT_Inter/PJT_Inter/Views/Funcionario/Login.cshtml
@model Funcionario
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Bem Vindo</h1>
                                </div>
                                <br />

                                <form asp-controller="Funcionario" asp-action="Login" method="post">
                                    <div class="form-group">
                                        <label asp-for="Email"></label>
                                        <input asp-for="Email" class="form-control " id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Digite seu Email">
                                        <span asp-validation-for="Email"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Senha"></label>
                                        <input asp-for="Senha" type="password" class="form-control " id="exampleInputPassword" placeholder="Password">
                                        <span asp-validation-for="Senha"></span>
                                    </div>
                                    <span>@ViewBag.Mensagem</span>
                                    <button class="btn btn-primary btn-user btn-block"> Login </button>
                                    <hr>
                                </form>
                                <br />
                                <div class="text-center">
                                    <a class="small" href="/Funcionario/CreateLogin">Criar uma Conta</a>
                                </div>
                                <br />
                                <br />

                                <br />
                                <br />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PJT_Inter/PJT_Inter/Views/Funcionario/Update.cshtml
@model Funcionario
<h2>Editar - Funcionario</h2>

<form asp-controller="Funcionario" asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" placeholder="Nome" />
        <span asp-validation-for="Nome"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" placeholder="E-Mail" />
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="Senha"></label>
        <input asp-for="Senha" class="form-control" placeholder="Senha" />
        <span asp-validation-for="Senha"></span>
    </div>
    <div class="form-group">
        <label>Endereço</label>
        <input asp-for="Endereco" class="form-control" placeholder="Endereço" />
        <span asp-validation-for="Endereco"></span>
    </div>
    <div class="form-group">
        <div class="form-row">
            <div class="col">
                <label asp-for="CPF_CNPJ"></label>
                <input asp-for="CPF_CNPJ" class="form-control" placeholder="CPF/CNPJ">
                <span asp-validation-for="CPF_CNPJ"></span>
            </div>
            <div class="col">
                <label asp-for="Telefone"></label>
                <input asp-for="Telefone" class="form-control" placeholder="Telefone">
                <span asp-validation-for="Telefone"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="form-row">
            <div class="col">
                <label asp-for="Salario"></label>
                <input asp-for="Salario" class="form-control" placeholder="Salario">
                <span asp-validation-for="Salario"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="form-check form-check-inline">
            <input asp-for="Status" class="form-check-input" type="radio" name="status" id="inlineCheckbox1" value="1">
            <span asp-validation-for="Status">Ativo</span>
        </div>
        <div class="form-check form-check-inline">
            <input asp-for="Status" class="form-check-input" type="radio" name="status" id="inlineCheckbox1" value="2">
            <span asp-validation-for="Status">Inativo</span>
        </div>
    </div>
    <button class="btn btn-primary ">Salvar</button>
</form>