PJT_Inter/PJT_Inter/Models/OsServ.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PJT_Inter.Models
{
    public class OsServ
    {
        // os_serv_equip(#os_id, #sevico_id, valor, quantidade, status)

        [Display(Name = "Ordem de serviço")]
        [Required(ErrorMessage = "Campo ordem de serviço obrigatório")]
        public int Os_Id { get; set; }

        [Display(Name = "Serviço")]
        [Required(ErrorMessage = "Campo serviço obrigatório")]
        public int Servico_Id { get; set; }

        [Display(Name = "Em Andamento/Finalizado")]
        [Required(ErrorMessage = "Campo status obrigatório")]
        public int Status { get; set; }

        public string NomeServico { get; set; }

        public string statusNome { get; set; }

    }
}

PJT_Inter/PJT_Inter/Controllers/OsServController.cs
using Microsoft.AspNetCore.Mvc;
using PJT_Inter.Data;
using PJT_Inter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PJT_Inter.Controllers
{
    public class OsServController : Controller
    {
        public IActionResult Index(int id)
        {
            List<OsServ> a = new List<OsServ>();

            using (var data = new OsServData())
            {
                a = data.CarregaServicos(id);
                @ViewBag.id_Os = id;


                return View(a);
            }
        }
        public IActionResult Create(int id)
        {

            List<Servico> servicos = new List<Servico>();

            using (var data = new OsServData())
            {
                servicos = data.ServicosNaoExistente(id);
                ViewBag.Servicos = servicos;
                ViewBag.id_Os = id;
            }
            return View();
        }
        [HttpPost]
        public IActionResult Create(int os, List<int> ser)
        {
            using (var data = new OsServData())
                data.Create(ser, os);

            return Redirect("/OsServ/Index/" + os);
        }
        public IActionResult Enviar(int id)
        {
            ViewBag.id_Os = id;
            return Redirect("/OsServ/Create/" + id);
        }


        public IActionResult Update(string P1, string P2)
        {
            
            ViewBag.servico_id = P2;
            ViewBag.os_id = P1;

             return View();
        }
        [HttpPost]
        public IActionResult Update(int servico_id, int os_id, int status)
        {
            OrdemServico os = new OrdemServico();


            using (var data = new OsServData())
            {
                data.Update(os_id, servico_id, status);    
            }

            return Redirect("/OsServ/Index/" + os_id);
        }
    }
}

PJT_Inter/PJT_Inter/Views/OsServ/Create.cshtml
@model OsServ



    <h2>Cadastro - Serviços na Ordem de Serviços</h2>
    <form asp-controller="OsServ" asp-action="Create" method="post" ng-app="">
        <hr>
        <div class="form-group">
            <input name="os" hidden value="@ViewBag.id_Os" />
        </div>

        <select name="ser" asp-for="Servico_Id" class="form-control">
            <option value="">Selecioner o Serviço</option>
            @foreach (var item in ViewBag.Servicos)
            {
                
                <option value="@item.ID_Servico">@item.Nome</option>
            }
        </select>
        <input class="form-group" type="checkbox" ng-model="checkbox" ng-init="checkbox = false">
        <label for="customControlInline">Deseja adicionar outro Equipamento ou Serviço?</label>
        <br />
        <div ng-if="checkbox">
            <div class="form-group">
                <select name="ser" class="form-control">
                    <option value="">Selecioner o Serviço</option>
                    @foreach (var item in ViewBag.Servicos)
                    {
                        <option value="@item.ID_Servico">@item.Nome</option>
                    }
                </select>
            </div>

            <input class="form-group" type="checkbox" ng-model="checkbox1" ng-init="checkbox1 = false">
            <label for="customControlInline">Deseja adicionar outro Equipamento ou Serviço?</label>
            <div ng-if="checkbox1">
                <div class="form-group">
                    <select asp-for="Servico_Id" name="ser" class="form-control">
                        <option value="">Selecioner o Serviço</option>
                        @foreach (var item in ViewBag.Servicos)
                        { 
                            <option value="@item.ID_Servico">@item.Nome</option>
                        }
                    </select>
                </div>
            </div>
        </div>

        <button class="btn btn-primary ">Salvar</button>
    </form>

PJT_Inter/PJT_Inter/Views/OsServ/Index.cshtml
@model List<OsServ>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
                Lista de Serviços da Ordem de Serviço
                    <a class="btn btn-primary" style="float: right" href="/OsServ/Create/@ViewBag.id_Os">Adicionar</a>
     
            </h6>
        </div>
        <form asp-controller="OsServ" asp-action="Index" method="get">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Serviço</th>
                        <th scope="col">Status</th>
                        <th scope="col">Editar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var oss in Model)
                    {
                        <tr>
                            <th scope="row">@oss.NomeServico</th>
                            <th scope="row">@oss.statusNome</th>
                            <th>
                                @*<a href="Home/Parametros/?P1=valor1&P2=valor2">Ativar</a>*@

                                <a class="btn btn-info btn-circle btn-sm" href="/OsServ/Update/?P1=@oss.Os_Id&P2=@oss.Servico_Id">
                                    <i class="fas fa-info-circle"></i>
                                </a>
                            </th>
                        </tr>    
                    }
                    
                </tbody>
            </table>
        </form>
    </div>

<a class="btn btn-primary" href="/OrdemServico/Index">Voltar</a>

PJT_Inter/PJT_Inter/Views/OsServ/Update.cshtml
@model OsServ

<h2>Editar - Status do Serviço da Ordem de Serviço</h2>
<form asp-controller="OsServ" asp-action="Update" method="post">
    <hr>
    <div class="form-group">
        <input name="servico_id" hidden value="@ViewBag.servico_id" />
    </div>
    <div class="form-group">
        <input name="os_id" hidden value="@ViewBag.os_id" />
    </div>

    <div class="form-group">
        <div class="form-check form-check-inline">
            <input asp-for="Status" type="radio" name="status" id="inlineCheckbox1" value="1">
            <span asp-validation-for="Status" style="margin-left: 5px">Aguardando Confirmação</span>
            <div class="form-check form-check-inline" style="margin-left: 10px">
                <input asp-for="Status" type="radio" name="status" id="inlineCheckbox1" value="2">
                <span asp-validation-for="Status" style="margin-left: 5px">Em Andamento</span>
            </div>
            <div class="form-check form-check-inline" style="margin-left: 10px">
                <input asp-for="Status" type="radio" name="status" id="inlineCheckbox1" value="3">
                <span asp-validation-for="Status" style="margin-left: 5px">Finalizado</span>
            </div>
            <div class="form-check form-check-inline" style="margin-left: 10px">
                <input asp-for="Status" type="radio" name="status" id="inlineCheckbox1" value="4">
                <span asp-validation-for="Status" style="margin-left: 5px">Cancelado</span>
            </div>
        </div>
    </div>

    <button class="btn btn-primary ">Salvar</button>
</form>